export const ALL_REDIRECT_REPORT_REQUEST = "ALL_REDIRECT_REPORT_REQUEST";
export const ALL_REDIRECT_REPORT_SUCCESS = "ALL_REDIRECT_REPORT_SUCCESS";
export const ALL_REDIRECT_REPORT_FAIL = "ALL_REDIRECT_REPORT_FAIL";